'---------------------------------------------------------------------------------------
' Class    : VBASyncImport.cls
' Version   : 3.4.0
' Purpose   :
'---------------------------------------------------------------------------------------
Option Explicit

Public FilePath As String
Public ComponentName As String
Public code As String
Public Extension As String
Public Attempt As Long
Public OriginalIndex As Long
